chess_website/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('accounts/admin/', admin.site.urls, name="admin_site"),
    path('', include('tournaments.urls')),
    path('accounts/', include('login.urls')),
    path("__reload__/", include("django_browser_reload.urls")),
]

login/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

app_name = 'login'
urlpatterns = [
    path("", include("django.contrib.auth.urls")),
    path("register/", views.register, name="register"),
    path("logout1/", views.logout_view, name="logout"),
]

tournaments/urls.py
from django.urls import path
from . import views

app_name = 'tournaments'
urlpatterns = [
    path('', views.index, name='index'),
    path('brackets/', views.brackets_list, name='brackets'),
    # /brackets/table/1
    path('brackets/table/<int:id>', views.bracket, name='bracket'),
    path('brackets/add', views.add_bracket, name='add_bracket'),
    path('brackets/table/<int:id>/add', views.add_players, name='add_players'),
    path('brackets/table/<int:id>/edit', views.edit_players, name='edit_players'),
    path('brackets/table/<int:id>/rounds/<int:round>', views.rounds, name='rounds'),
    path('brackets/table/<int:id>/rounds/<int:round>/edit', views.edit_rounds, name='edit_rounds'),
    path('brackets/table/<int:id>/rounds/<int:round>/add', views.add_round, name='add_round'),
]

tournaments/models.py
from django.db import models
# Create your models here.


class Bracket(models.Model):
    size = models.PositiveIntegerField(default=0)
    name = models.CharField(max_length=200)
    date = models.DateTimeField(
        'tournament date',
        null=True,
        blank=True
    )
    numberOfRounds = models.PositiveIntegerField(default=1)

    def __str__(self):
        date = str(self.date) if self.date else ""
        return str(self.name) + " " + date


class Player(models.Model):
    name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    age = models.PositiveIntegerField()
    rating = models.PositiveIntegerField(
        null=True,
        blank=True,
    )
    score = models.FloatField(
        default=0,
        null=True,
    )
    score_round = models.FloatField(
        default=0,
        null=True,
    )
    bracket = models.ForeignKey(
        Bracket,
        null=True,
        blank=True,
        on_delete=models.CASCADE,
    )  # many to one relation

    def __str__(self):
        return f"{self.name} {self.last_name}"


class Rounds(models.Model):
    round = models.PositiveIntegerField(default=1)
    player1_id = models.PositiveIntegerField(null=True, blank=True)
    player2_id = models.PositiveIntegerField(null=True, blank=True)
    player1_score = models.FloatField(null=True, default=0)
    player2_score = models.FloatField(null=True, default=0)
    bracket = models.ForeignKey(
        Bracket,
        null=True,
        blank=True,
        on_delete=models.CASCADE,
    )
    isFinished = models.BooleanField(default=False)

    def __str__(self):
        player1_name = Player.objects.get(pk=self.player1_id).name if self.player1_id else ""
        player2_name = Player.objects.get(pk=self.player2_id).name if self.player2_id else ""

        return f"{self.bracket.name} {self.round} | {player1_name} vs {player2_name}"

tournaments/forms.py
from django import forms
from django.forms import ModelForm
from .models import Bracket, Player


class BracketForm(ModelForm):
    class Meta:
        model = Bracket
        fields = ('name', 'date', "numberOfRounds")
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-element'}),
            'date': forms.DateInput(attrs={'class': 'form-element'}),
            "numberOfRounds": forms.NumberInput(attrs={'class': 'form-element'}),
        }

class PlayersForm(ModelForm):
    class Meta:
        model = Player
        fields = ('name', 'last_name', 'age', 'rating', 'score')

tournaments/views.py
from django.db.models import Sum
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.forms import inlineformset_factory
from django.contrib.auth.decorators import permission_required

from .models import Bracket, Player, Rounds
from .forms import BracketForm, PlayersForm

# Create your views here.


def index(response):
    return render(response, 'tournaments/index.html', {})


def brackets_list(response):
    brackets = Bracket.objects.all()
    size = []
    for x in brackets:
        size.append(Player.objects.filter(bracket=x).count())

    br = zip(brackets, size)
    return render(response, 'tournaments/brackets_list.html', {'brackets': br})


def bracket(response, id):
    bracket = get_object_or_404(Bracket, pk=id)
    players = Player.objects.filter(bracket=id).all()

    refresh_score(id)

    response.session['sorting'] = ""
    # persist sorting session variable
    if response.GET.get('sort'):
        response.session['sorting'] = response.GET.get('sort')
    else:
        response.session['sorting']
    field_names = [f.name for f in Player._meta.get_fields()]
    field_names_desc = ['-' + f.name for f in Player._meta.get_fields()]

    match response.session['sorting']:
        case x:
            if x in field_names:
                players = players.order_by(str(x))
            elif x in field_names_desc:
                players = players.order_by(str(x))
            else:
                players = players.order_by('pk')
    context = {
        'bracket': bracket,
        'players': players,
        'response': response,
    }
    return render(response, 'tournaments/bracket.html', context)

@permission_required('tournaments.moderator')
def add_bracket(response):
    submitted = False
    if response.method == 'POST':
        form = BracketForm(response.POST)
        if form.is_valid():
            form.save()
            bracket_id = Bracket.objects.latest('id').id
            nuber_of_rounds = Bracket.objects.latest('id').numberOfRounds
            create_rounds(bracket_id, nuber_of_rounds)
            return HttpResponseRedirect('/brackets/add?submitted=True')
    else:
        form = BracketForm
        if 'submitted' in response.GET:
            submitted = True
    context = {'form': form, 'submitted': submitted}
    return render(response, 'tournaments/add_bracket.html', context)


@permission_required('tournaments.moderator')
def add_players(response, id):
    bracket = Bracket.objects.get(pk=id)
    if response.method == "POST":
        form = PlayersForm(response.POST)
        if form.is_valid():
            player = form.save(commit=False)
            player.bracket = bracket
            form.save()
            return HttpResponseRedirect('/brackets/table/' + str(id))

    else:
        form = PlayersForm()
    context = {'form': form}
    return render(response, 'tournaments/add_players.html', context)


@permission_required('tournaments.moderator')
def edit_players(response, id):
    bracket = Bracket.objects.get(pk=id)
    PlayerInlineFormSet = inlineformset_factory(
        Bracket, Player, fields=['name', 'last_name', 'age', 'rating', 'score'])
    if response.method == 'POST':
        formset = PlayerInlineFormSet(response.POST, response.FILES, instance=bracket)
        if formset.is_valid():
            formset.save()
            return HttpResponseRedirect('/brackets/table/' + str(id))
    else:
        formset = PlayerInlineFormSet(instance=bracket)
    context = {'form': formset}
    return render(response, 'tournaments/edit_players.html', context)


def rounds(response, id, round):
    bracket = get_object_or_404(Bracket, pk=id)
    players = Player.objects.filter(bracket=id).all()
    rounds = Rounds.objects.filter(bracket=id).filter(round=round).all()

    refresh_round_score(id, round)

    # # if round in rounds table get score from rounds table for each half of players and sort them by rating if round is 0 or score if round is > 0
    if round > 1:
        first_half = players.filter(id__in=rounds.values('player1_id'))
        second_half = players.filter(id__in=rounds.values('player2_id'))
    else:
        players = players.order_by("-rating")
        first_half = players[:len(players)//2]
        second_half = players[len(players)//2:]

    
    # first_half, second_half = sort_players(id, round)


    context = {
        'first_half': first_half,
        'second_half': second_half,
        'bracket': bracket,
        'rd': str(round),
        'rounds_number': range(1,bracket.numberOfRounds+1)
    }
    return render(response, 'tournaments/rounds.html', context)


@permission_required('tournaments.moderator')
def edit_rounds(response, id, round):
    bracket = get_object_or_404(Bracket, pk=id)
    rounds = Rounds.objects.filter(bracket=bracket).filter(round=round).all()


    # create_rounds(id, bracket.numberOfRounds)
    first_half, second_half = sort_players(id, round)
    for p1, p2 in zip(first_half, second_half):
        create_round_and_add_players(id, round, p1.id, p2.id)

    players1 = Player.objects.filter(id__in=rounds.values('player1_id')).order_by("-rating")
    players2 = Player.objects.filter(id__in=rounds.values('player2_id')).order_by("-rating")

    

    if response.method == 'POST':
        for player in players1:
            if(response.POST.get("p1" + str(player.pk))) != '':
                rounds.filter(player1_id=player.pk).update(player1_score=int(response.POST.get("p1" + str(player.pk))))
                player.score = rounds.filter(player1_id=player.pk).aggregate(Sum('player1_score'))['player1_score__sum']
                player.score_round = rounds.filter(player1_id=player.pk).get().player1_score
                player.save()

        for player in players2:
            if(response.POST.get("p2" + str(player.pk))) != '':
                rounds.filter(player2_id=player.pk).update(player2_score=int(response.POST.get("p2" + str(player.pk))))
                player.score = rounds.filter(player2_id=player.pk).aggregate(Sum('player2_score'))['player2_score__sum']
                player.score_round = rounds.filter(player2_id=player.pk).get().player2_score
                player.save()

        # if round is mark as Finished call add_players_to_round function
        if response.POST.get("finished") == 'on':
            print("finised")
            # set round as finished
            rd = Rounds.objects.filter(bracket=bracket).filter(round=round)
            print(rd)
            for r in rd:
                print(r.id, r.isFinished)
                r.isFinished = True
                print(r.id, r.isFinished)
                r.save()
            if round+1 in rounds.values('round') and rounds.last().isFinished == True:
                print("debug add players")
                # add_players_to_round(id, round+1)

        return HttpResponseRedirect('/brackets/table/' + str(id) + "/rounds/" + str(round))

    context = {
        'rounds': rounds,
        'bracket': bracket,
        'rd': round,
        'players1': players1,
        'players2': players2,
    }
    return render(response, 'tournaments/edit_rounds.html', context)


@permission_required('tournaments.moderator')
def add_round(response, id, round):
    bracket = get_object_or_404(Bracket, pk=id)
    
    bracket.numberOfRounds = bracket.numberOfRounds + 1
    bracket.save(update_fields=['numberOfRounds'])

    return rounds(response, id, round)

def refresh_round_score(bracket_id, round_id):
    bracket = get_object_or_404(Bracket, pk=bracket_id)
    round = Rounds.objects.filter(bracket=bracket).filter(round=round_id).all()
    players = Player.objects.filter(bracket=bracket).all()
    for player in players:
        s1, s2 = 0, 0
        if round.filter(player1_id=player.pk).first() is not None:
            s1 = round.filter(player1_id=player.pk).first().player1_score or 0
        if round.filter(player2_id=player.pk).first() is not None:
            s2 = round.filter(player2_id=player.pk).first().player2_score or 0
        player.score_round = s1 + s2
        player.save()


def refresh_score(bracket_id):
    bracket = get_object_or_404(Bracket, pk=bracket_id)
    rounds = Rounds.objects.filter(bracket=bracket).all()
    players = Player.objects.filter(bracket=bracket).all()
    for player in players:
        s1 = rounds.filter(player1_id=player.pk).aggregate(Sum('player1_score')).get('player1_score__sum') or 0
        s2 = rounds.filter(player2_id=player.pk).aggregate(Sum('player2_score')).get('player2_score__sum') or 0
        player.score = s1 + s2
        player.save()

def create_rounds(bracket_id, nuber_of_rounds):
    bracket = get_object_or_404(Bracket, pk=bracket_id)
    for i in range(1, nuber_of_rounds + 1):
        if Rounds.objects.filter(bracket=bracket, round=i).exists() == False:
            round = Rounds.objects.create(bracket=bracket, round=i, isFinished=False)
            round.save()

def add_players_to_round(bracket_id, round_id, player1_id, player2_id, player1_score=0, player2_score=0):
    round_obj = get_object_or_404(Rounds, pk=round_id)
    if round_obj.player1_id is None:
        round_obj.player1_id = player1_id
        round_obj.player1_score = player1_score
    if round_obj.player1_id is None:
        round_obj.player2_id = player2_id
        round_obj.player2_score = player2_score
    round_obj.save()

def create_round_and_add_players(bracket_id, round_number, player1_id, player2_id, player1_score=0, player2_score=0):
    bracket = get_object_or_404(Bracket, pk=bracket_id)
    round_obj, created  = Rounds.objects.get_or_create(bracket=bracket, round=round_number, isFinished=False, player1_id=player1_id, player2_id=player2_id)

    round_obj.save()


def sort_players(bracket_id, round):
    players = Player.objects.filter(bracket=bracket_id).all()

tournaments/templates/tournaments/add_bracket.html
{% extends 'tournaments/base.html' %}
{% block content %}

<div class="center">
	<h1>Add New Bracket</h1>
</div>
<section>
	{% if submitted %}
	<p>Your bracket was created!</p>
	{% else %}
	<form action="" method=POST>
		{% csrf_token %}
		{{form.as_p}}
		<button type="submit" class="btn-form" >Sumbit</button>
	</form>
	{% endif %}
</section>

{% endblock content %}

tournaments/templates/tournaments/add_players.html
{% extends 'tournaments/base.html' %}
{% block content %}

<div class="center">
	<h1>Add New Bracket</h1>
</div>
<section>
	<form action="" method=POST class="form-grid">
		{% csrf_token %}
		{{form.as_p}}
		<button type="submit" class="btn-form" >Sumbit</button>
	</form>
</section>

{% endblock content %}

tournaments/templates/tournaments/base.html
{% load static %}
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="{% static 'style.css' %}" />
	<title>Chess Website</title>
</head>

<body>
	<header>
		<!-- <img src="" alt="Logo"> -->
		<h1 class="logo">Logo</h1>
		<input type="checkbox" class="nav-toggle" id="nav-toggle">
		<nav class="text-nav">
			<ul>
				<li><a href="{% url 'tournaments:index' %}">HOME</a></li>
				<li><a href="{% url 'tournaments:brackets' %}">TOURNAMENTS</a></li>
				{% if user.is_authenticated %}
				  <li><a href="{% url 'admin:index' %}">MANAGE</a></li>
				  <li><a class="nav-logout" href="{% url 'login:logout' %}">Hello {{user.username}}</a></li>
				{% else %}
				  <li><a class="nav-btn" href="{% url 'login:login' %}">LOGIN</a></li>
				{% endif %}
			</ul>
		</nav>
		<label for="nav-toggle" class="nav-toggle-label">
			<span></span>
		</label>
	</header>
	<div class="spacer"></div>
	<div>
	{% block content %}

	{% endblock content %}
	</div>
	<footer>
		footer
	</footer>
</body>

</html>

tournaments/templates/tournaments/bracket.html
{% extends 'tournaments/base.html' %}
{% block content %}

<section>
	{% if players %}
	<table>
		<thead>
			<tr>
				<th><a href="/brackets/table/{{bracket.id}}?sort=name">Name</a></th>
				<th><a href="/brackets/table/{{bracket.id}}?sort=last_name">Last name</a></th>
				<th><a href="/brackets/table/{{bracket.id}}?sort=age">Age</a></th>
				<th><a href="/brackets/table/{{bracket.id}}?sort=-rating">Rating</a></th>
				<th><a href="/brackets/table/{{bracket.id}}?sort=-score">Score</a></th>
			</tr>
		</thead>
		<tbody>
			{% for player in players %} <tr>
				<td scope="row"> {{player.name}}</td>
				<td> {{player.last_name}}</td>
				<td> {{player.age}}</td>
				<td> {{player.rating}}</td>
				<td> {{player.score}}</td>
			</tr>
			{% endfor %}
			{% else %}
			<p>Empty</p>
		</tbody>
		{% endif %}
	</table>
	<div class="inline-container">
		<a class="button btn-form" href="{% url 'tournaments:brackets' %}">back</a>
		{% if perms.tournament.moderator %}
		<a class="button btn-form" href="{% url 'tournaments:add_players' id=bracket.id %}">Add</a>
		<a class="button btn-form" href="{% url 'tournaments:edit_players' id=bracket.id %}">Edit</a>
		{% endif %}
		<a class="button btn-form" href="{% url 'tournaments:rounds' id=bracket.id round=1 %}">Rounds</a>
	</div>
</section>

{% endblock content %}

tournaments/templates/tournaments/brackets_list.html
{% extends 'tournaments/base.html' %}
{% block content %}

<section>
	<table>
		<thead>
			<tr>
				<th>Tournament Name</th>
				<th>Number Of Players</th>
				<th>Date</th>
				<th>Options</th>
			</tr>
		</thead>
		<tbody>
			{% if brackets %}
			{% for bracket, len in brackets%}
			<tr>
				<td scope="row"> {{bracket.name}}</td>
				<td> {{len}}</td>
				<td> {{bracket.date}}</td>
				<td>
					<a class="button" href="{% url 'tournaments:bracket' id=bracket.id %}">Players List</a>
					<a class="button" href="{% url 'tournaments:rounds' id=bracket.id round=1%}">Rounds</a></td>
				{% endfor %}
			</tr>
			{% else %}
			<p>Empty</p>
			{% endif %}
		</tbody>
	</table>
	<div class="inline-container">
	{% if perms.tournament.moderator %}
	<a class="button btn-form" href="{% url 'tournaments:add_bracket' %}">Add</a>
	{% endif %}
	</div>
</section>

{% endblock content %}

tournaments/templates/tournaments/edit_players.html
{% extends 'tournaments/base.html' %}
{% block content %}

<div class="center">
	<h1>Add New Bracket</h1>
</div>
<section>
	<form action="" method=POST class="form-inline">
		{% csrf_token %}
		{{form.as_p}}
		<div class="break"></div>
		<button type="submit" class="btn-form" >Sumbit</button>
	</form>
</section>

{% endblock content %}

tournaments/templates/tournaments/edit_rounds.html
{% extends 'tournaments/base.html' %}
{% block content %}

<section>
  round: {{rd}}
	<div class='inline-section'>
		<form action="" method=POST class='form-inline'>
			{% csrf_token %}
			<table>
				<thead>
					<tr>
						<th>Name</a></th>
						<th>Last name</a></th>
						<th>Age</a></th>
						<th>Rating</a></th>
						<th>Score</a></th>
					</tr>
				</thead>
				<tbody>
					{% for player in players1 %} <tr>
						<td scope="row"> {{player.name}}</td>
						<td> {{player.last_name}}</td>
						<td> {{player.age}}</td>
						<td> {{player.rating}}</td>
						<td><input type="number" name="p1{{ player.id }}" {{player.score}}></td>
						{% endfor %}
					</tr>
				</tbody>
			</table>
			<table>
				<thead>
					<tr>
						<th>Score</th>
						<th>Rating</a></th>
						<th>Age</a></th>
						<th>Last name</a></th>
						<th>Name</a></th>
					</tr>
				</thead>
				<tbody>
					{% for player in players2 %} <tr>
						<td scope="row"><input type="number" name="p2{{ player.id }}" {{player.score}}></td>
						<td> {{player.rating}}</td>
						<td> {{player.age}}</td>
						<td> {{player.last_name}}</td>
						<td> {{player.name}}</td>
						{% endfor %}
					</tr>
				</tbody>
			</table>
			<div class="break"></div>
				<input type="checkbox" name="finished" id="finished">
				<label for="finished">Round was finished</label>
			<div class="inline-container">
				<button class="btn-form" type="submit">submit</button>
				<a class="button btn-form" href="{% url 'tournaments:rounds' id=bracket.id round=rd%}">back</a>
			</div>
		</form>
	</div>
</section>

{% endblock content %}

tournaments/templates/tournaments/index.html
{% extends 'tournaments/base.html' %}

{% block content %}
<body class="bg-img">
<div class="home-text">
	
<h2 class="big-text center">Chess Tournaments</h2> 
<div class="text center"
		<p>This website used to create or to look for chess tournaments. Click on tournaments to see list of them.</p>
</div>

<section></section>

<section class="text">
		<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta architecto incidunt reiciendis cum perferendis, esse consectetur sint corrupti sed explicabo eaque impedit, dolores, dignissimos quasi non ipsa saepe provident mollitia!</p>
</section>
</div>
</body>
{% endblock content %}

tournaments/templates/tournaments/rounds.html
{% extends 'tournaments/base.html' %}
{% block content %}
{% load tags %}

<section>
	<h2>Round: {{ rd }}</h2>
	<div class="form-inline">
		<table>
			<thead>
				<tr>
					<th><a href="/brackets/table/{{bracket.id}}?sort=name">Name</a></th>
					<th><a href="/brackets/table/{{bracket.id}}?sort=last_name">Last name</a></th>
					<th><a href="/brackets/table/{{bracket.id}}?sort=rating">Rating</a></th>
					<th><a href="/brackets/table/{{bracket.id}}?sort=score">Score</a></th>
				</tr>
			</thead>
			<tbody>
				{% for player in first_half %} <tr>
					<td scope="row"> {{player.name}}</td>
					<td> {{player.last_name}}</td>
					<td> {{player.rating}}</td>
					<td> {{player.score_round}}</td>
					{% endfor %}
				</tr>
			</tbody>
		</table>
		<table>
			<thead>
				<tr>
					<th><a href="/brackets/table/{{bracket.id}}?sort=score">Score</a></th>
					<th><a href="/brackets/table/{{bracket.id}}?sort=rating">Rating</a></th>
					<th><a href="/brackets/table/{{bracket.id}}?sort=last_name">Last name</a></th>
					<th><a href="/brackets/table/{{bracket.id}}?sort=name">Name</a></th>
				</tr>
			</thead>
			<tbody>
				{% for player in second_half %} <tr>
					<td scope="row"> {{player.score_round}}</td>
					<td> {{player.rating}}</td>
					<td> {{player.last_name}}</td>
					<td> {{player.name}}</td>
					{% endfor %}
				</tr>
			</tbody>
		</table>
	</div>
	<div class="inline-container">
		<a class="button btn-form" href="{% url 'tournaments:brackets' %}">back</a>
	  {% for x in rounds_number %}
	  <a class="button btn-form" href="{% url 'tournaments:rounds' id=bracket.id round=x %}">{{x}}</a>
	  {% endfor %}
		{% if perms.tournament.moderator %}
		<a class="button btn-form" href="{% url 'tournaments:edit_rounds' id=bracket.id round=rd%}">update score</a>
		<a class="button btn-form" href="{% url 'tournaments:add_round' id=bracket.id round=1 %}">add round</a>
		{% endif %}
	</div>
<!--	<div class="break"></div>-->
<!--	<div>-->
<!--		<form action="" method=POST>-->
<!--			{% csrf_token %}-->
<!--			<button class="btn-form" type="submit">save db</button>-->
<!--		</form>-->
<!--	</div>-->
</section>

{% endblock content %}